### ISSUE TITLE
I got invalid concurrent access delete

### ISSUE THREAD

**Issue by Akekarat** [GrahamDennis/GDCoreDataConcurrencyDebugging#14]
Hi

I just tried this library. It looks promising. But when I tried it I got this 

> Invalid concurrent access to managed object calling 'release'; Stacktrace: (
>     0   atlascopcoconstruction-ios          0x00353e5b ValidateConcurrency + 267
>     1   atlascopcoconstruction-ios          0x00353a54 CustomSubclassRelease + 36
>     2   libobjc.A.dylib                     0x03f1deb1 objc_release + 65
>     3   libobjc.A.dylib                     0x03f1de68 objc_storeStrong + 39
>     4   atlascopcoconstruction-ios          0x001118d4 -[ACCCDataManager(Parsing) getRootProductFileWithContext:] + 452
>     5   atlascopcoconstruction-ios          0x00198d75 -[ACCCDataManager getAllSizeTextWithContext:] + 85
>     6   atlascopcoconstruction-ios          0x00168357 __42-[SettingsViewController reloadFolderSize]_block_invoke + 327
>     7   libdispatch.dylib                   0x04792c2a _dispatch_call_block_and_release + 15
>     8   libdispatch.dylib                   0x047b008f _dispatch_client_callout + 14
>     9   libdispatch.dylib                   0x0479a342 _dispatch_root_queue_drain + 671
>     10  libdispatch.dylib                   0x0479b592 _dispatch_worker_thread2 + 45
>     11  libsystem_pthread.dylib             0x04b02dab _pthread_wqthread + 336
>     12  libsystem_pthread.dylib             0x04b06cce start_wqthread + 30
> )

I use autoreleasepool, and I got this at the end of autoreleasepool block. It's in the same thread.

> ```
> @autoreleasepool{
>     NSPredicate *filterPredicate = [NSPredicate predicateWithFormat:@"name = %@", @"PRODUCT"];
>     NSFetchRequest *fileRequest = [CDFile MR_requestAllWithPredicate:filterPredicate inContext:context];
>     NSArray *files = [CDFile MR_executeFetchRequest:fileRequest inContext:context];
>     if(files.count == 0){
>     }else{
>         if(files.count > 1){
>             LogWarning(@"There are %d CDFile with 'PRODUCT' name", files.count);
>         }
>         cdFile = [files objectAtIndex:0];
>     }
> }   <----------- THIS LINE
> ```

My code and this library code are called in same thread.

This is my stack trace.
![screen shot 2014-08-14 at 1 11 07 pm](https://cloud.githubusercontent.com/assets/2211391/3919141/bd6f5026-23a3-11e4-9095-d5c9cc0de5a9.png)

**Comment by simonbromberg** [comment]
Fetch requests need to be created inside `performBlockAndWait`?

**Comment by GrahamDennis** [comment]
Fetch requests don't need to be created inside `performBlockAndWait`, but any interactions with an `NSManagedObject` outside of a `[context performBlock...:]` method are potentially dangerous, particularly if you ever call `[context reset]`.  In this case, one solution would be to return an `NSManagedObjectID` for the `CDFile` rather than the `CDFile` itself.

Another solution would be to require the method calling `getRootProductFileWithContext` to call `[context performBlockAndWait:...]`.
