### ISSUE TITLE
The Podspec is pointing to an old version.

### ISSUE THREAD

**Issue by PadraigK** [GrahamDennis/GDCoreDataConcurrencyDebugging#16]
The 0.1 tag is from March 2014, but there are commits from Jan 2015 - the latest should be tagged and the podspec updated.

**Comment by dtweston** [comment]
The podspec has been updated now, but it hasn't been pushed to the cocoapods master spec repo. :-/

This pod is amazing, and has been really helpful for me. Is there some way the community can help with maintenance?

**Comment by lemonkey** [comment]
I had to fork this repo and add it to my private specs repo for now.

**Comment by GrahamDennis** [comment]
Sorry for the lack of responses. I have now published a new 0.4 tag and updated the podspec in the CocoaPods repo. Please let me know if there are any problems.
