### ISSUE TITLE
Can't install v. 0.2

### ISSUE THREAD

**Issue by balazsnemeth** [GrahamDennis/GDCoreDataConcurrencyDebugging#18]
My pod file:
pod 'GDCoreDataConcurrencyDebugging', '~> 0.2'

After pod install:

[!] Unable to satisfy the following requirements:
- `GDCoreDataConcurrencyDebugging (~> 0.2)` required by `Podfile`

**Comment by rcarlsen** [comment]
I believe that the maintainer needs to push the latest podspec to the canonical specs repo.
In the meantime, you can modify your Podfile to use the tag from this repo:
```
pod "GDCoreDataConcurrencyDebugging", :git => 'git@github.com:GrahamDennis/GDCoreDataConcurrencyDebugging.git', :tag => '0.2', :configurations => ['Debug']
```

**Comment by rcarlsen** [comment]
I also had to use :submodules => true, per:
http://www.geero.net/2014/06/using-submodules-in-cocoapods-sourced-from-git/

**Comment by lemonkey** [comment]
You could also fork the repo and add it to your private specs repo if you need to use it as a subspec dependency in a local dev pod that's a framework in your app...

**Comment by GrahamDennis** [comment]
I've now pushed 0.4.  Let me know if there are any problems.
