### ISSUE TITLE
What's the benefit of using this pod?

### ISSUE THREAD

**Issue by pronebird** [GrahamDennis/GDCoreDataConcurrencyDebugging#21]
What the benefit of this pod vs. com.apple.CoreData.ConcurrencyDebug ?

**Comment by GrahamDennis** [comment]
I am not familiar with that. I'm going to guess that it's more recent than my project, and hopefully Apple's tool picks up a superset of issues that my library picks up. 

I don't have a good answer for you. I'd suggest you try both and let me know whether either one catches issues that the other doesn't. But I'm sure Apple's tool is easier to use :-)

**Comment by GrahamDennis** [comment]
It seems that com.apple.CoreData.ConcurrencyDebug doesn't identify 'release' or 'dealloc' messages sent outside of the appropriate context.  i.e. it doesn't seem to notice the issue I fixed in @haemi's test project here: https://github.com/GrahamDennis/ConcurrencyDebugging/commit/f33f7bca1284ad7acb031ca8608f61450c45e97a

**Comment by pronebird** [comment]
I am sure it is legal to release nsmanagedobject on any thread, esp. because in arc we don't have much control over it. The same way you can use .objectID on any thread, what's illegal is to access properties that would otherwise query the context.

**Comment by GrahamDennis** [comment]
Not in every situation unfortunately. See http://www.grahamdennis.me/blog/2013/09/09/debugging-concurrency-with-core-data

**Comment by pronebird** [comment]
Cheers, that amazes me that Magical Record has a method -inContext: on objects which invites you to pass objects around.



—
Cheers,
Andrej

**Comment by GrahamDennis** [comment]
If you don't delete objects you will be ok. You may be ok if you delete but not reset the MOC. The issue I hit & described in the blog article was hit by resetting the MOC.

**Comment by somerobots** [comment]
Hi I'm using Magical Record 2.2 and I'm hitting some deadlock issues. I've started to investigate where these issues might be, your insight on any do's and don'ts would be really helpful!

**Comment by GrahamDennis** [comment]
I don't use MagicalRecord... Or even CoreData any more. Also this project can't help (I think) with deadlocks, just when you're doing something outside of a performBlock call.

**Comment by somerobots** [comment]
Graham, thank you. Yeah I just spent the entire day auditing the app for areas that don't access data inside performBlock. This was very helpful for me.

I still get deadlocks though in ```NSFetchedResultsController``` ```performFetch``` :(

**Comment by GrahamDennis** [comment]
I haven't abandoned Core Data, I just haven't worked on any iOS stuff at all in quite some time.  Real work has been busy.
