### ISSUE TITLE
Invalid concurrent access to managed object calling 'release'; on recursive saving of context

### ISSUE THREAD

**Issue by shanthivardhan** [GrahamDennis/GDCoreDataConcurrencyDebugging#22]
Hi,
I am using a helper function to save context recursively and my code looks like following snippet. When I added GDCoreDataConcurrencyDebugging to my workspace it keep showing "Invalid concurrent access to managed object calling 'release'; Stacktrace" whenever a save happens to the context. Could you please let me what is going wrong in the following snippet. I added "-com.apple.CoreData.ConcurrencyDebug 1" and this concurrency issue is not getting captured with the argument.
 
+ (void) saveManagedObjectContext:(NSManagedObjectContext *)managedObjectContext
                   withCompletion:(void (^)(NSError * saveError))completion {
    
    [managedObjectContext performBlock:^{
        NSError	*error	= nil;
        if (![managedObjectContext save:&error]){
            if (completion) {
                completion(error);
            }
        } else {            
            if ([managedObjectContext parentContext] != nil){
                [CoreDataController saveManagedObjectContext:[managedObjectContext parentContext] withCompletion:completion];                
            } else {
                if (completion) {                
                    completion(error);
                }
            }
        }
    }];
}

====================

 Invalid concurrent access to managed object calling 'release'; Stacktrace: (
	0   SampleApp                              0x0033ee45 ValidateConcurrency + 366
	1   SampleApp                              0x0033eb2a CustomSubclassRelease + 23
	2   CoreData                            0x0109cd3d -[NSSQLConstantValueIntermediate dealloc] + 45
	3   libobjc.A.dylib                     0x043d6060 _ZN11objc_object17sidetable_releaseEb + 238
	4   libobjc.A.dylib                     0x043d7320 -[NSObject release] + 25
	5   CoreData                            0x0109c15a -[NSSQLIntermediate _generateSQLForConstantValue:inContext:] + 122
	6   CoreData                            0x010a88ce -[NSSQLIntermediate _generateSQLForConstantCollection:inContext:] + 334
	7   CoreData                            0x010a80ad -[NSSQLSimpleWhereIntermediate _generateSQLContainmentStringInContext:] + 1821
	8   CoreData                            0x01099b56 -[NSSQLSimpleWhereIntermediate generateSQLStringInContext:] + 582
	9   CoreData                            0x01098f46 -[NSSQLFetchIntermediate generateSQLStringInContext:] + 118
	10  CoreData                            0x011c943a -[NSSQLGenerator newSQLStatementForRequest:ignoreInheritance:countOnly:nestingLevel:nestIsWhereScoped:] + 522
	11  CoreData                            0x010942f9 -[NSSQLGenerator newSQLStatementForFetchRequest:ignoreInheritance:countOnly:nestingLevel:nestIsWhereScoped:] + 73
	12  CoreData                            0x011aa32a -[NSSQLAdapter _statementForFetchRequest:ignoreInheritance:countOnly:nestingLevel:] + 442
	13  CoreData                            0x01094168 -[NSSQLAdapter _newSelectStatementWithFetchRequest:ignoreInheritance:] + 392
	14  CoreData                            0x01093fd0 -[NSSQLAdapter newSelectStatementWithFetchRequest:] + 48
	15  CoreData                            0x01093d52 -[NSSQLCore newRowsForFetchPlan:] + 130
	16  CoreData                            0x0109354d -[NSSQLCore objectsForFetchRequest:inContext:] + 573
	17  CoreData                            0x01092ebf -[NSSQLCore executeRequest:withContext:error:] + 591
	18  CoreData                            0x01199750 __65-[NSPersistentStoreCoordinator executeRequest:withContext:error:]_block_invoke + 5120
	19  CoreData                            0x011a3fff gutsOfBlockToNSPersistentStoreCoordinatorPerform + 191
	20  libdispatch.dylib                   0x05de89cd _dispatch_client_callout + 14
	21  libdispatch.dylib                   0x05dcaada _dispatch_barrier_sync_f_invoke + 156
	22  libdispatch.dylib                   0x05dca242 dispatch_barrier_sync_f + 98
	23  CoreData                            0x01192ac7 _perform + 183
	24  CoreData                            0x01092a1f -[NSPersistentStoreCoordinator executeRequest:withContext:error:] + 431
	25  CoreData                            0x01090e69 -[NSManagedObjectContext executeFetchRequest:error:] + 649
	26  CoreData                            0x01169408 __92-[NSManagedObjectContext(_NSInternalChangeProcessing) _prefetchObjectsForDeletePropagation:]_block_invoke + 200
	27  CoreFoundation                      0x04d65839 ____NSDictionaryEnumerate_block_invoke417 + 41
	28  CoreFoundation                      0x04c482c2 CFBasicHashApply + 130
	29  CoreFoundation                      0x04c85321 __NSDictionaryEnumerate + 273
	30  CoreFoundation                      0x04c8518d -[NSDictionary enumerateKeysAndObjectsWithOptions:usingBlock:] + 45
	31  CoreFoundation                      0x04c850d5 -[NSDictionary enumerateKeysAndObjectsUsingBlock:] + 53
	32  CoreData                            0x01169298 -[NSManagedObjectContext(_NSInternalChangeProcessing) _prefetchObjectsForDeletePropagation:] + 296
	33  CoreData                            0x010df6c1 -[NSManagedObjectContext(_NSInternalChangeProcessing) _processDeletedObjects:] + 1217
	34  CoreData                            0x010c2f67 -[NSManagedObjectContext(_NSInternalChangeProcessing) _propagatePendingDeletesAtEndOfEvent:] + 119
	35  CoreData                            0x010bdd2a -[NSManagedObjectContext(_NSInternalChangeProcessing) _processRecentChanges:] + 2010
	36  CoreData                            0x010bd536 -[NSManagedObjectContext processPendingChanges] + 54
	37  CoreData                            0x010e775e -[NSManagedObjectContext(_NestedContextSupport) _parentProcessSaveRequest:inContext:error:] + 2014
	38  CoreData                            0x0116c6fc __82-[NSManagedObjectContext(_NestedContextSupport) executeRequest:withContext:error:]_block_invoke + 412
	39  CoreData                            0x010e1c5c internalBlockToNSManagedObjectContextPerform + 76
	40  libdispatch.dylib                   0x05de89cd _dispatch_client_callout + 14
	41  libdispatch.dylib                   0x05dcaada _dispatch_barrier_sync_f_invoke + 156
	42  libdispatch.dylib                   0x05dca242 dispatch_barrier_sync_f + 98
	43  CoreData                            0x010e1b7e _perform + 206
	44  CoreData                            0x010e19ce -[NSManagedObjectContext(_NestedContextSupport) executeRequest:withContext:error:] + 238
	45  CoreData                            0x010c24e3 -[NSManagedObjectContext save:] + 1379
	46  SampleApp                              0x00240073 __59+[CoreDataController saveManagedObjectContext:withCompletion:]_block_invoke + 53
	47  CoreData                            0x010e170a developerSubmittedBlockToNSManagedObjectContextPerform + 202
	48  libdispatch.dylib                   0x05de89cd _dispatch_client_callout + 14
	49  libdispatch.dylib                   0x05dcdf90 _dispatch_main_queue_callback_4CF + 910
	50  CoreFoundation                      0x04cb85fe __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	51  CoreFoundation                      0x04c762f4 __CFRunLoopRun + 2356
	52  CoreFoundation                      0x04c75706 CFRunLoopRunSpecific + 470
	53  CoreFoundation                      0x04c7551b CFRunLoopRunInMode + 123
	54  GraphicsServices                    0x0650d664 GSEventRunModal + 192
	55  GraphicsServices                    0x0650d4a1 GSEventRun + 104
	56  UIKit                               0x021071eb UIApplicationMain + 160
	57  SampleApp                              0x000f1657 main + 336
	58  libdyld.dylib                       0x05e12a21 start + 1
	59  ???                                 0x00000003 0x0 + 3
)

**Comment by GrahamDennis** [comment]
Please give the latest version in git a try.  I think this issue has been fixed, and I really need to create a new release.

**Comment by shanthivardhan** [comment]
Thank you for the response I tried it with Cocoapods will give it a try with latest version in git.
